import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
  try {
    // Get pagination parameters from URL
    const { searchParams } = new URL(req.url);
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "10");

    // Load courses from localStorage simulation (in production, fetch from database)
    // Since this is a server-side API route, we'll use mock data
    // Client can still check localStorage and merge
    
    const mockCourses = [
      // YouTube Playlist Courses (Free)
      {
        id: "1",
        title: "Sigma Development Course",
        description: "Web Development Tutorials in Hindi - Complete full-stack development course covering HTML, CSS, JavaScript, React, Node.js and more. Perfect for beginners starting their web development journey.",
        link: "https://youtube.com/playlist?list=PLu0W_9lII9agq5TrH9XLIKQvv0iaF2X3w&si=y_HUKb0e0bhTOQeM",
        uploadType: "youtube",
        category: "Web Development",
        level: "Beginner",
        duration: "40+ hours",
        enrollmentCount: 15420,
        rating: 4.9,
        views: 45670,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "/thumbnails/hqdefault.jpg",
        instructor: "CodeWithHarry",
        materials: [
          { type: "video", name: "YouTube Playlist", url: "https://youtube.com/playlist?list=PLu0W_9lII9agq5TrH9XLIKQvv0iaF2X3w" },
          { type: "link", name: "Course Notes", url: "https://www.codewithharry.com" },
        ],
      },
      {
        id: "2",
        title: "Ultimate Python Course",
        description: "Python for Beginners Full Course - Learn Python programming from scratch with hands-on projects. Covers basics, data structures, OOP, file handling, and popular libraries.",
        link: "https://youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg&si=5B14--USWRXTv0rp",
        uploadType: "youtube",
        category: "Programming",
        level: "Beginner",
        duration: "35+ hours",
        enrollmentCount: 12890,
        rating: 4.8,
        views: 38920,
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "/thumbnails/hqdefault1.jpg",
        instructor: "CodeWithHarry",
        materials: [
          { type: "video", name: "YouTube Playlist", url: "https://youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg" },
          { type: "link", name: "Python Documentation", url: "https://docs.python.org" },
        ],
      },
      {
        id: "3",
        title: "Probability and Statistics",
        description: "Complete course on Probability and Statistics - Master statistical concepts, probability theory, distributions, hypothesis testing, and data analysis techniques.",
        link: "https://youtube.com/playlist?list=PLxCzCOWd7aiFjZP4z1_3Kr3m3J5Jwu5Q8V&si=6pDuvF1KLARJgzSD",
        uploadType: "youtube",
        category: "Mathematics",
        level: "Intermediate",
        duration: "25+ hours",
        enrollmentCount: 8540,
        rating: 4.7,
        views: 24310,
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "/thumbnails/hqdefault2.jpg",
        instructor: "Statistics Expert",
        materials: [
          { type: "video", name: "YouTube Playlist", url: "https://youtube.com/playlist?list=PLxCzCOWd7aiFjZP4z1_3Kr3m3J5Jwu5Q8V" },
          { type: "pdf", name: "Formula Sheet", url: "/materials/stats-formulas.pdf" },
        ],
      },
      {
        id: "4",
        title: "Digital Logic Design (DLD) Complete Course",
        description: "Full course on Digital Logic Design - Learn boolean algebra, logic gates, combinational and sequential circuits, flip-flops, counters, and memory systems.",
        link: "https://youtube.com/playlist?list=PLgWOIdHQBEz6Ougd453k22nyPDNoNw_tX&si=5giLW8WpcoooBrNK",
        uploadType: "youtube",
        category: "Computer Science",
        level: "Intermediate",
        duration: "30+ hours",
        enrollmentCount: 9720,
        rating: 4.8,
        views: 28650,
        createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "/thumbnails/hqdefault3.jpg",
        instructor: "DLD Academy",
        materials: [
          { type: "video", name: "YouTube Playlist", url: "https://youtube.com/playlist?list=PLgWOIdHQBEz6Ougd453k22nyPDNoNw_tX" },
          { type: "pdf", name: "Circuit Diagrams", url: "/materials/dld-circuits.pdf" },
        ],
      },
      // Additional Mock Courses
      {
        id: "course_789",
        title: "Intro to Math",
        description: "Master the basics of mathematics including algebra, geometry, and calculus fundamentals. Perfect for beginners looking to build a strong foundation.",
        link: "/mock-math.pdf",
        uploadType: "file",
        category: "Mathematics",
        level: "Beginner",
        duration: "4 weeks",
        enrollmentCount: 1250,
        rating: 4.8,
        views: 3450,
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400",
        instructor: "Dr. Sarah Johnson",
        materials: [
          { type: "pdf", name: "Course Syllabus", url: "/syllabus.pdf" },
          { type: "video", name: "Introduction Video", url: "https://youtube.com/watch?v=example1" },
          { type: "pdf", name: "Practice Problems", url: "/practice.pdf" },
        ],
      },
      {
        id: "course_790",
        title: "Web Development Fundamentals",
        description: "Learn HTML, CSS, and JavaScript from scratch. Build responsive websites and understand modern web development practices.",
        link: "https://www.youtube.com/watch?v=web-dev-course",
        uploadType: "link",
        category: "Programming",
        level: "Beginner",
        duration: "6 weeks",
        enrollmentCount: 2340,
        rating: 4.9,
        views: 5670,
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400",
        instructor: "Prof. Michael Chen",
        materials: [
          { type: "link", name: "Course Website", url: "https://webdev101.com" },
          { type: "video", name: "HTML Basics", url: "https://youtube.com/watch?v=html" },
          { type: "video", name: "CSS Styling", url: "https://youtube.com/watch?v=css" },
          { type: "video", name: "JavaScript Intro", url: "https://youtube.com/watch?v=js" },
        ],
      },
      {
        id: "course_791",
        title: "Data Science with Python",
        description: "Dive into data science using Python. Learn pandas, NumPy, and machine learning basics. Includes hands-on projects and real-world datasets.",
        link: "/data-science-python.pdf",
        uploadType: "file",
        category: "Data Science",
        level: "Intermediate",
        duration: "8 weeks",
        enrollmentCount: 1890,
        rating: 4.7,
        views: 4230,
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
        instructor: "Dr. Emily Rodriguez",
        materials: [
          { type: "pdf", name: "Python Basics", url: "/python-basics.pdf" },
          { type: "pdf", name: "Pandas Guide", url: "/pandas-guide.pdf" },
          { type: "link", name: "Jupyter Notebooks", url: "https://github.com/course/notebooks" },
        ],
      },
      {
        id: "course_792",
        title: "Digital Marketing Essentials",
        description: "Master digital marketing strategies including SEO, social media marketing, content marketing, and analytics. Perfect for entrepreneurs and marketers.",
        link: "https://www.coursera.org/digital-marketing",
        uploadType: "link",
        category: "Business",
        level: "Beginner",
        duration: "5 weeks",
        enrollmentCount: 1560,
        rating: 4.6,
        views: 3890,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
        instructor: "Sarah Williams",
        materials: [
          { type: "pdf", name: "SEO Guide", url: "/seo-guide.pdf" },
          { type: "link", name: "Marketing Tools", url: "https://tools.example.com" },
        ],
      },
      {
        id: "course_793",
        title: "Advanced React Patterns",
        description: "Take your React skills to the next level with advanced patterns, hooks, performance optimization, and state management techniques.",
        link: "/advanced-react.pdf",
        uploadType: "file",
        category: "Programming",
        level: "Advanced",
        duration: "6 weeks",
        enrollmentCount: 980,
        rating: 4.9,
        views: 2340,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400",
        instructor: "Alex Thompson",
        materials: [
          { type: "pdf", name: "React Patterns", url: "/react-patterns.pdf" },
          { type: "link", name: "Code Examples", url: "https://github.com/react-advanced" },
          { type: "video", name: "Performance Tips", url: "https://youtube.com/watch?v=perf" },
        ],
      },
      {
        id: "course_794",
        title: "UI/UX Design Principles",
        description: "Learn the fundamentals of user interface and user experience design. Create beautiful, functional designs using Figma and modern design tools.",
        link: "https://www.udemy.com/ui-ux-design",
        uploadType: "link",
        category: "Design",
        level: "Beginner",
        duration: "4 weeks",
        enrollmentCount: 2100,
        rating: 4.8,
        views: 4560,
        createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400",
        instructor: "Jessica Lee",
        materials: [
          { type: "link", name: "Figma Templates", url: "https://figma.com/templates" },
          { type: "pdf", name: "Design Principles", url: "/design-principles.pdf" },
        ],
      },
      {
        id: "course_795",
        title: "Machine Learning Basics",
        description: "Introduction to machine learning algorithms and concepts. Learn supervised and unsupervised learning with practical examples.",
        link: "/ml-basics.pdf",
        uploadType: "file",
        category: "Data Science",
        level: "Intermediate",
        duration: "10 weeks",
        enrollmentCount: 1450,
        rating: 4.7,
        views: 3120,
        createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400",
        instructor: "Dr. James Park",
        materials: [
          { type: "pdf", name: "ML Algorithms", url: "/ml-algorithms.pdf" },
          { type: "link", name: "Python Code", url: "https://github.com/ml-course" },
        ],
      },
      {
        id: "course_796",
        title: "Business Strategy & Planning",
        description: "Learn strategic planning, business model development, and competitive analysis. Essential for entrepreneurs and business leaders.",
        link: "https://www.linkedin.com/learning/business-strategy",
        uploadType: "link",
        category: "Business",
        level: "Intermediate",
        duration: "6 weeks",
        enrollmentCount: 1120,
        rating: 4.5,
        views: 2890,
        createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400",
        instructor: "David Kumar",
        materials: [
          { type: "pdf", name: "Strategy Framework", url: "/strategy-framework.pdf" },
          { type: "link", name: "Case Studies", url: "https://cases.example.com" },
        ],
      },
      {
        id: "course_797",
        title: "Photography Masterclass",
        description: "From beginner to pro photographer. Learn composition, lighting, editing, and storytelling through images.",
        link: "/photography-masterclass.pdf",
        uploadType: "file",
        category: "Creative Arts",
        level: "Beginner",
        duration: "7 weeks",
        enrollmentCount: 1780,
        rating: 4.9,
        views: 4120,
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400",
        instructor: "Maria Santos",
        materials: [
          { type: "pdf", name: "Camera Settings", url: "/camera-guide.pdf" },
          { type: "video", name: "Composition Tips", url: "https://youtube.com/watch?v=comp" },
          { type: "link", name: "Photo Gallery", url: "https://gallery.example.com" },
        ],
      },
      {
        id: "course_798",
        title: "Cybersecurity Fundamentals",
        description: "Protect your digital assets. Learn about network security, encryption, ethical hacking, and security best practices.",
        link: "https://www.cybrary.it/course/cybersecurity-fundamentals",
        uploadType: "link",
        category: "Technology",
        level: "Intermediate",
        duration: "8 weeks",
        enrollmentCount: 1340,
        rating: 4.8,
        views: 3670,
        createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400",
        instructor: "Robert Zhang",
        materials: [
          { type: "pdf", name: "Security Basics", url: "/security-basics.pdf" },
          { type: "link", name: "Lab Environment", url: "https://labs.cybersec.com" },
        ],
      },
      {
        id: "course_799",
        title: "Creative Writing Workshop",
        description: "Develop your writing skills across fiction, non-fiction, and poetry. Learn storytelling techniques and find your unique voice.",
        link: "/creative-writing.pdf",
        uploadType: "file",
        category: "Creative Arts",
        level: "Beginner",
        duration: "5 weeks",
        enrollmentCount: 1650,
        rating: 4.7,
        views: 3210,
        createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
        instructor: "Emma Wilson",
        materials: [
          { type: "pdf", name: "Writing Prompts", url: "/writing-prompts.pdf" },
          { type: "link", name: "Writing Community", url: "https://writers.example.com" },
        ],
      },
      {
        id: "course_800",
        title: "Financial Planning 101",
        description: "Personal finance basics including budgeting, investing, retirement planning, and building wealth. Take control of your financial future.",
        link: "https://www.khanacademy.org/finance",
        uploadType: "link",
        category: "Finance",
        level: "Beginner",
        duration: "4 weeks",
        enrollmentCount: 2450,
        rating: 4.8,
        views: 5340,
        createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        thumbnail: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400",
        instructor: "Jennifer Brown",
        materials: [
          { type: "pdf", name: "Budget Template", url: "/budget-template.pdf" },
          { type: "link", name: "Investment Calculator", url: "https://calc.finance.com" },
        ],
      },
    ];

    // Pagination logic
    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;
    const paginatedCourses = mockCourses.slice(startIndex, endIndex);
    const hasMore = endIndex < mockCourses.length;

    return NextResponse.json({
      success: true,
      courses: paginatedCourses,
      pagination: {
        page,
        limit,
        total: mockCourses.length,
        hasMore,
        totalPages: Math.ceil(mockCourses.length / limit),
      },
    });
  } catch (error) {
    console.error("Error fetching courses:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch courses" },
      { status: 500 }
    );
  }
}
